<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TravelloB8\Module'                   => __DIR__ . '/Module.php',
    'TravelloB8\Service\B8ServiceFactory' => __DIR__ . '/src/TravelloB8/Service/B8ServiceFactory.php',
    'TravelloB8\Service\B8Service'        => __DIR__ . '/src/TravelloB8/Service/B8Service.php',
    'b8_storage_mysql'                    => __DIR__ . '/vendor/b8/b8/storage/storage_mysql.php',
    'b8_storage_dba'                      => __DIR__ . '/vendor/b8/b8/storage/storage_dba.php',
    'b8_storage_base'                     => __DIR__ . '/vendor/b8/b8/storage/storage_base.php',
    'b8_lexer_default'                    => __DIR__ . '/vendor/b8/b8/lexer/lexer_default.php',
    'b8_degenerator_default'              => __DIR__ . '/vendor/b8/b8/degenerator/degenerator_default.php',
    'b8'                                  => __DIR__ . '/vendor/b8/b8/b8.php',
);